---
version: "2"

linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: all

  # Enable specific linter.
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - canonicalheader
    # - containedctx
    # - contextcheck
    # - copyloopvar
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    # - err113
    - errcheck
    # - errchkjson
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustruct
    # - exptostd
    # - fatcontext
    # - forbidigo
    # - forcetypeassert
    # - funcorder
    # - funlen
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    # - gocognit
    - goconst
    # - gocritic
    - gocyclo
    # - godot
    # - godox
    # - goheader
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    - gosec
    # - gosmopolitan
    - govet
    # - grouper
    # - iface
    # - importas
    # - inamedparam
    - ineffassign
    # - interfacebloat
    # - intrange
    # - ireturn
    # - lll
    # - loggercheck
    # - maintidx
    # - makezero
    # - mirror
    # - misspell
    # - mnd
    # - musttag
    # - nakedret
    # - nestif
    # - nilerr
    # - nilnesserr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    # - reassign
    # - recvcheck
    - revive
    # - rowserrcheck
    # - sloglint
    # - spancheck
    # - sqlclosecheck
    # - staticcheck
    # - tagalign
    # - tagliatelle
    # - testableexamples
    # - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    - unconvert
    # - unparam
    - unused
    # - usestdlibvars
    # - usetesting
    # - varnamelen
    # - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint

  # Disable specific linter.
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    # - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    # - goconst
    - gocritic
    # - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec
    - gosmopolitan
    # - govet
    - grouper
    - iface
    - importas
    - inamedparam
    # - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    # - unconvert
    - unparam
    # - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - max-lit-count: "10"
              allow-strs: '""'
              allow-ints: "0,1,2,3,4,5,6,7,8,9"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
        # More than 50 issues
        - name: cognitive-complexity
          disabled: true
        # More than 50 issues
        - name: cyclomatic
          disabled: true
        - name: empty-lines
          disabled: true
        # More than 50 issues
        - name: exported
          disabled: true
        # More than 50 issues
        - name: function-length
          disabled: true
        - name: line-length-limit
          severity: warning
          disabled: false
          arguments: [80]
        - name: package-comments
          disabled: true
        # More than 50 issues
        - name: unchecked-type-assertion
          disabled: true
